#!/bin/bash
# Script to sync local repository to Cloud Composer GCS bucket using gsutil rsync
# 
# Syncs:
#   - dags/ → gs://<bucket>/dags/ (includes dags/scripts/, dags/config/, dags/dvc_project/)
# 
# Single source of truth:
#   - dags/scripts/ and dags/config/ are used for both local development and Composer
#   - Composer only syncs the dags/ folder; keep all DAG dependencies inside dags/
#
# DVC Repository Notes:
#   - The DVC repo used by Composer lives under dags/dvc_project/
#   - The script's rsync command (gsutil -m rsync -r -d dags/ gs://$COMPOSER_BUCKET/dags/)
#     will sync the DVC repo automatically as part of the dags/ directory
#   - The root-level .dvc/ and dvc.yaml are primarily for local development

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get project root (script location)
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Get the actual Composer bucket (not the terraform-created one)
echo -e "${YELLOW}📦 Getting Composer bucket name...${NC}"
COMPOSER_BUCKET=$(gcloud composer environments describe mlops-airflow-composer \
  --location us-central1 \
  --project break-the-bot-480422 \
  --format="value(config.dagGcsPrefix)" 2>/dev/null | sed 's|/dags$||' | sed 's|^gs://||' || echo "")

if [ -z "$COMPOSER_BUCKET" ]; then
    echo -e "${RED}❌ Error: Could not get Composer bucket. Make sure Composer environment exists.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Composer Bucket: ${COMPOSER_BUCKET}${NC}"
echo ""

# Check if gsutil is available
if ! command -v gsutil &> /dev/null; then
    echo -e "${RED}❌ Error: gsutil is not installed or not in PATH${NC}"
    echo "   Install Google Cloud SDK: https://cloud.google.com/sdk/docs/install"
    exit 1
fi

# Check authentication
if ! gsutil ls gs://${COMPOSER_BUCKET}/ > /dev/null 2>&1; then
    echo -e "${YELLOW}⚠️  Warning: Could not verify bucket access, but continuing anyway...${NC}"
    echo -e "${YELLOW}   If sync fails, please authenticate with:${NC}"
    echo "   gcloud auth login"
    echo "   gcloud auth application-default login"
    # Don't exit - continue and let gsutil commands fail if auth is really broken
fi

echo -e "${YELLOW}🚀 Starting sync to Cloud Composer...${NC}"
echo ""

# 0. Verify dags/scripts/ exists (single source of truth)
echo -e "${YELLOW}[0/3] Verifying dags/scripts/ exists...${NC}"
if [ -d "dags/scripts" ]; then
    echo -e "${GREEN}✓ dags/scripts/ found (single source of truth)${NC}"
    echo ""
else
    echo -e "${RED}❌ Error: dags/scripts/ directory not found${NC}"
    echo -e "${RED}   All scripts must be in dags/scripts/ (single source of truth)${NC}"
    exit 1
fi

# 1. Sync dags/ directory (EXCLUDING data files to prevent overwriting DAG-generated data)
echo -e "${YELLOW}[1/4] Syncing dags/ → gs://${COMPOSER_BUCKET}/dags/...${NC}"
if [ -d "dags" ]; then
    # CRITICAL: Exclude dvc_project/data/ to prevent overwriting DAG-generated data files
    # Data files are generated by DAG runs in Composer and should NOT be synced from local
    echo -e "${YELLOW}   Excluding dags/dvc_project/data/ to preserve DAG-generated files${NC}"
    
    # Sync DAG Python files first (the actual DAG definitions)
    echo "   Syncing DAG Python files (*.py) from dags/ root..."
    for dag_file in dags/*.py; do
        if [ -f "$dag_file" ]; then
            FILENAME=$(basename "$dag_file")
            gsutil cp "$dag_file" gs://${COMPOSER_BUCKET}/dags/$FILENAME
            echo "     ✓ Synced: $FILENAME"
        fi
    done
    
    # Sync specific directories, excluding data/
    echo "   Syncing dags/scripts/..."
    gsutil -m rsync -r -d dags/scripts/ gs://${COMPOSER_BUCKET}/dags/scripts/
    
    echo "   Syncing dags/config/..."
    gsutil -m rsync -r -d dags/config/ gs://${COMPOSER_BUCKET}/dags/config/
    
    echo "   Syncing dags/dvc_project/ (excluding data/)..."
    # Sync .dvc directory
    if [ -d "dags/dvc_project/.dvc" ]; then
        gsutil -m rsync -r -d dags/dvc_project/.dvc/ gs://${COMPOSER_BUCKET}/dags/dvc_project/.dvc/
    fi
    
    # For dvc.yaml and dvc.lock: Always pull latest from Composer first (DAG may have updated them)
    # This ensures we don't overwrite newer files generated by DAG runs
    echo "   Pulling latest dvc.yaml and dvc.lock from Composer..."
    if gsutil -q cp gs://${COMPOSER_BUCKET}/dags/dvc_project/dvc.yaml dags/dvc_project/dvc.yaml 2>/dev/null; then
        echo "     ✓ Updated local dvc.yaml from Composer"
    else
        echo "     ⚠️  dvc.yaml not found in Composer (will sync local version)"
    fi
    
    if gsutil -q cp gs://${COMPOSER_BUCKET}/dags/dvc_project/dvc.lock dags/dvc_project/dvc.lock 2>/dev/null; then
        echo "     ✓ Updated local dvc.lock from Composer (may have been updated by DAG)"
    else
        echo "     ⚠️  dvc.lock not found in Composer (will sync local version)"
    fi
    
    # Then sync local versions back to Composer (in case you made local changes)
    # This ensures bidirectional sync: Composer → Local → Composer
    if [ -f "dags/dvc_project/dvc.yaml" ]; then
        gsutil cp dags/dvc_project/dvc.yaml gs://${COMPOSER_BUCKET}/dags/dvc_project/dvc.yaml
        echo "     ✓ Synced dvc.yaml to Composer"
    fi
    if [ -f "dags/dvc_project/dvc.lock" ]; then
        gsutil cp dags/dvc_project/dvc.lock gs://${COMPOSER_BUCKET}/dags/dvc_project/dvc.lock
        echo "     ✓ Synced dvc.lock to Composer"
    fi
    
    echo -e "${GREEN}✓ dags/ directory synced${NC}"
    echo "   (includes *.py DAG files, dags/scripts/, dags/config/, dags/dvc_project/.dvc/, dags/dvc_project/dvc.yaml)"
    echo -e "${YELLOW}   ⚠️  Note: dags/dvc_project/data/ was EXCLUDED (preserves DAG-generated data)${NC}"
else
    echo -e "${RED}⚠️  Warning: dags directory not found${NC}"
fi
echo ""

# Note: Root-level data/ is NOT synced - data files are generated by the DAG when it runs.
#       Config is kept inside dags/config/ for Composer compatibility.
#       Root-level DVC files are for local dev; Composer uses dags/dvc_project/.

# 2. Verify syncs
echo -e "${YELLOW}[2/4] Verifying syncs...${NC}"
echo ""
echo -e "${YELLOW}Checking DAG Python files:${NC}"
gsutil ls gs://${COMPOSER_BUCKET}/dags/*.py 2>/dev/null | head -5 || echo "  (no .py files found)"
echo ""
echo -e "${YELLOW}Checking dags/:${NC}"
gsutil ls gs://${COMPOSER_BUCKET}/dags/ 2>/dev/null | head -5 || echo "  (empty or error)"
echo ""
echo -e "${YELLOW}Checking dags/scripts/:${NC}"
gsutil ls gs://${COMPOSER_BUCKET}/dags/scripts/ 2>/dev/null | head -5 || echo "  (empty or error)"
echo ""
echo -e "${YELLOW}Checking dags/dvc_project/:${NC}"
gsutil ls gs://${COMPOSER_BUCKET}/dags/dvc_project/ 2>/dev/null | head -5 || echo "  (empty or error)"
echo ""
echo -e "${YELLOW}Checking dags/config/:${NC}"
gsutil ls gs://${COMPOSER_BUCKET}/dags/config/ 2>/dev/null | head -5 || echo "  (empty or error)"
echo ""

echo -e "${GREEN}✅ Sync complete!${NC}"
echo ""
echo -e "${YELLOW}📋 Next steps:${NC}"
echo "1. Wait 1-2 minutes for Airflow to discover the DAG"
echo "2. Access Airflow UI: https://3a25b0f9a1414af2a5480c386fe042da-dot-us-central1.composer.googleusercontent.com"
echo "3. Look for DAG: salad_ml_evaluation_pipeline_v1"
echo "4. Set Airflow Variables (Admin → Variables):"
echo "   - TEST_MODE: false"
echo "   - HF_TOKEN: (from Secret Manager)"
echo "   - GROQ_API_KEY: (from Secret Manager)"
echo "   - AIRFLOW__SMTP__SMTP_USER: (from Secret Manager)"
echo "   - AIRFLOW__SMTP__SMTP_PASSWORD: (from Secret Manager)"
echo "5. Toggle DAG ON and trigger a test run"
echo ""
echo -e "${YELLOW}💡 To set secrets automatically, run:${NC}"
echo "   cd terraform && ./setup-secrets.sh"
echo ""
echo -e "${YELLOW}📦 Composer Bucket: ${COMPOSER_BUCKET}${NC}"
echo ""
echo -e "${YELLOW}ℹ️  Note: project-root/scripts/ is NOT synced (Composer uses dags/scripts/ instead)${NC}"
